### ISSUE TITLE
Add basic README

### ISSUE THREAD

**Issue by jpstrikesback** [react-navigation/react-navigation-web#1]
Hey I'd love to test, perhaps hack on this, and know if it's a viable approach. Any chance a super minimal README could be added detailing:

- The idea/concept
- Any instructions
- Viability

Cheers!
JP

**Comment by JavaJamie** [comment]
Any update with this?

**Comment by geminiyellow** [comment]
hi @ericvicenti thanks for your work, but, you know,
no docs is very suck, thought it is a alpha version,

i try to copy the code and try to use it, but, hey

`react` not `React` in [here](https://github.com/react-navigation/react-navigation-web/blob/b0e22b132cd2aa17b61c2d27ad2aacb81ec9e1b8/src/react-navigation-web.js#L3),

and there is no [addNavigationHelpers](https://github.com/react-navigation/react-navigation-web/blob/b0e22b132cd2aa17b61c2d27ad2aacb81ec9e1b8/src/react-navigation-web.js#L5) in v2.x.

could you give more detail about this repo?

**Comment by ericvicenti** [comment]
Hey folks, here is the upcoming page for web support: https://reactnavigation.org/docs/en/next/web-support.html

Contributions and questions welcome!

**Comment by Kielan** [comment]
Please re open this issue, if you want help with contributors please have channels available to do so. Excited to see react-navigation supporting web!

**Comment by RWOverdijk** [comment]
2 years later:

> Support for web in React Navigation 5 is experimental and a work-in-progress. Documentation is coming soon.

😄

C'mon, let us in. Let us help!
