### ISSUE TITLE
query parameters from url not passed to route

### ISSUE THREAD

**Issue by sirpy** [react-navigation/react-navigation-web#45]
If I load a url localhost/?test=1
navigation.state.params will be empty
only when using navigation.navigateTo(route,params) it works

**Comment by 509dave16** [comment]
@sirpy Make sure you are using `createBrowserApp` from `react-navigation/web` instead of `createAppContainer` from `@react-navigation/core` for `web` platform. Container created by `createAppContainer` will not respond to url changes like it does when created by `createBrowserApp`.

**Comment by sirpy** [comment]
@509dave16 
i am using it. currently i have to parse the params from window.location myself

**Comment by sirpy** [comment]
@509dave16 
i've tested things again, this actually works, what doesnt work is this
https://github.com/react-navigation/web/issues/30
using navigation.navigate(route,params) doesnt set params in `navigation.state.parms`
