### ISSUE TITLE
Disallow functionality option for /gq route

### ISSUE THREAD

**Issue by Kielan** [react-navigation/react-navigation-web#7]
I am looking at a workaround for this, similar to a robots.txt Disallow option. Maybe this should be an option provided by react-navigation-web.

**Comment by satya164** [comment]
What's `gq` route?

**Comment by Kielan** [comment]
@satya164 It is common in dev environments to have a graphiql interface route for testing at /gq (according to docs)

My question is more broad however, other web routing solutions provide routes for params and other optional matching. I see however in this example repo the proper configuration syntax to refer to

https://github.com/react-navigation/example-web/blob/master/src/App.js
